package daemon

// pairingWords is the wordlist for invite/join pairing codes: 1024
// short, lowercase, easily-readable words. Eight words give 80 bits of
// entropy against active guessing (wrong words fail the WireGuard
// handshake); eight, not five, because the words also derive the
// pairing tunnel's static keys and a recorded handshake's MAC1 is an
// offline oracle (see pairing_mac1_test.go) — a precomputed 2^80
// candidate table is out of anyone's reach. TestPairingWords locks in
// the count and uniqueness.
var pairingWords = []string{
	"able", "acorn", "acre", "act", "adobe", "agora", "airy", "alarm",
	"album", "algae", "alias", "alibi", "alien", "alloy", "aloft", "amber",
	"amble", "angel", "anvil", "apple", "april", "apron", "arch", "arena",
	"armor", "arrow", "aspen", "aster", "atlas", "atom", "attic", "auburn",
	"audio", "aunt", "aura", "auto", "autumn", "avalanche", "avocado", "awake",
	"award", "axiom", "azalea",
	"bacon", "badge", "bagel", "baker", "balcony", "ballad", "bamboo", "banjo",
	"barn", "basil", "basin", "basket", "baton", "beach", "beacon", "beam",
	"bean", "bedrock", "beet", "beluga", "berry", "birch", "bishop", "bison",
	"blanket", "blaze", "blend", "blossom", "bluejay", "boat", "bobcat", "bonfire",
	"borax", "border", "boulder", "bracket", "bramble", "brass", "breeze", "bridge",
	"bright", "bronze", "brook", "bubble", "buckle", "burrow", "butter", "button",
	"cabin", "cactus", "cadet", "cairn", "camel", "camera", "canal", "candle",
	"canoe", "canvas", "canyon", "capital", "caramel", "cargo", "carrot", "castle",
	"cedar", "cello", "cement", "cereal", "chalk", "chamber", "cheer", "cherry",
	"chest", "chimney", "chisel", "chocolate", "cider", "cinnamon", "circus", "citrus",
	"clam", "clarinet", "clay", "clever", "cliff", "clover", "coast", "cobalt",
	"cocoa", "coffee", "comet", "compass", "copper", "coral", "cork", "corn",
	"cotton", "cougar", "coyote", "crab", "crayon", "creek", "cricket", "crimson",
	"crocus", "crow", "crystal", "cumin", "cupcake", "curry", "cypress",
	"dagger", "dahlia", "daisy", "dam", "dawn", "delta", "denim", "desert",
	"diamond", "dill", "dingo", "dock", "dolphin", "domino", "donkey", "dragon",
	"drama", "dream", "drift", "duck", "dune", "dusk", "dynamo",
	"eagle", "earth", "easel", "east", "eclipse", "elder", "elephant", "elm",
	"ember", "emerald", "engine", "envelope", "epsilon", "essay", "estate", "evening",
	"everest", "exit", "extra",
	"fable", "factory", "falcon", "fallow", "famous", "fan", "fennel", "fern",
	"ferry", "fiber", "fiddle", "fig", "finance", "finch", "fir", "firefly",
	"fisher", "fjord", "flag", "flamingo", "flannel", "flax", "fleet", "flint",
	"float", "flock", "florist", "flute", "foal", "focus", "fog", "forest",
	"fortune", "fox", "fragrant", "freeway", "frigate", "frog", "frost", "fuchsia",
	"gadget", "galaxy", "gallium", "garden", "garlic", "gazelle", "gecko", "gem",
	"general", "gentle", "geyser", "ghost", "giant", "ginger", "giraffe", "glacier",
	"glide", "glow", "goldfish", "gopher", "gorge", "granite", "grape", "grass",
	"gravity", "green", "grotto", "guitar", "gully", "gum", "gusto",
	"habitat", "haddock", "hall", "hammock", "harbor", "harmony", "harvest", "hazel",
	"heather", "hedge", "helmet", "heron", "hickory", "highway", "hill", "hollow",
	"honey", "hood", "horizon", "hornet", "hospital", "hound", "hummingbird", "hurricane",
	"iceberg", "igloo", "impact", "index", "indigo", "inlet", "inn", "iris",
	"iron", "island", "ivory", "ivy",
	"jacket", "jaguar", "jasmine", "jellyfish", "jewel", "jigsaw", "jonquil", "journal",
	"journey", "joystick", "jungle", "juniper",
	"kayak", "kernel", "kestrel", "kettle", "keystone", "kidney", "kingfisher", "kiwi",
	"kitten", "koala", "kombucha", "krypton",
	"label", "lace", "lagoon", "lake", "lantern", "lapel", "larch", "lark",
	"laser", "latex", "lavender", "leaf", "ledge", "lemon", "lentil", "leopard",
	"lettuce", "liberty", "lichen", "lifeboat", "lilac", "lily", "limber", "linden",
	"linen", "lion", "liter", "lizard", "llama", "lobster", "location", "locomotive",
	"lodge", "loft", "logic", "lotus", "lounge", "lucidity", "lumber", "lunar",
	"lyric",
	"macaw", "magnet", "mahogany", "mailbox", "mammal", "mango", "mantis", "maple",
	"marble", "marigold", "marsh", "mascot", "meadow", "medal", "melon", "mercury",
	"mesa", "meteor", "mica", "milk", "mimic", "mineral", "mint", "mirage",
	"mistletoe", "mitten", "monarch", "monsoon", "moonlight", "morning", "mosaic", "moss",
	"motel", "moth", "motorway", "mountain", "mouse", "muffin", "mulberry", "muscle",
	"museum", "mushroom", "mustard", "myrtle",
	"nacho", "nadir", "napkin", "narrative", "navy", "nebula", "nectar", "needle",
	"neon", "nest", "nettle", "newt", "nickel", "night", "nimbus", "noble",
	"nomad", "north", "notion", "nova", "nugget", "nutmeg", "nylon",
	"oasis", "oat", "ocean", "octave", "octopus", "olive", "omega", "onion",
	"onyx", "opal", "opera", "orbit", "orchard", "orchid", "oregano", "organic",
	"osprey", "ostrich", "otter", "outback", "outlet", "owl", "oyster",
	"pacifier", "paddle", "palace", "palm", "pancake", "panda", "pantry", "papaya",
	"parade", "parcel", "parsley", "parsnip", "pastel", "patriot", "pavement", "peach",
	"peanut", "pearl", "pebble", "pedal", "pelican", "pencil", "penguin", "peony",
	"pepper", "perfume", "petal", "phantom", "phone", "photon", "piano", "picnic",
	"pigeon", "pigment", "pilgrim", "pillar", "pillow", "pine", "pistol", "pixel",
	"pizza", "placid", "planet", "plank", "platinum", "plaza", "plum", "plume",
	"pocket", "poetry", "polaris", "pollen", "pomelo", "poncho", "poplar", "poppy",
	"porch", "possum", "potato", "prairie", "prance", "prawn", "pretzel", "prism",
	"prong", "pudding", "puffin", "pumpkin", "purse", "pyjama", "python",
	"quaint", "quarry", "quartz", "quench", "quilt", "quiver",
	"rabbit", "raccoon", "radar", "radish", "raft", "railway", "rainbow", "raisin",
	"rambler", "ranch", "raspberry", "raven", "ravine", "redwood", "reef", "relic",
	"reindeer", "relay", "rendezvous", "rhubarb", "ribbon", "ridge", "rifle", "ring",
	"ripple", "risotto", "river", "robin", "rocket", "rodeo", "rosemary", "roster",
	"rubber", "ruby", "rugby", "ruler", "rumor", "rustic",
	"saddle", "saffron", "sailboat", "salad", "salmon", "salsa", "sand", "sapphire",
	"satin", "scarf", "school", "scooter", "sculpture", "seagull", "seal", "season",
	"seaweed", "sediment", "sequoia", "serenade", "serpent", "shadow", "sherbet", "shore",
	"shrimp", "sierra", "signal", "silicon", "silk", "sinew", "siren", "sisal",
	"ski", "skiff", "skunk", "skyline", "slalom", "slate", "sledding", "slipper",
	"smoke", "snorkel", "snowfall", "soccer", "socket", "soda", "sofa", "solo",
	"sonata", "sorbet", "soybean", "spaniel", "spark", "sparrow", "spatula", "spice",
	"spider", "spinach", "spirit", "splash", "sponge", "spruce", "squall", "squash",
	"squid", "stable", "stadium", "stage", "stamp", "staple", "starling", "steam",
	"stone", "stopwatch", "storm", "stove", "straw", "stream", "street", "string",
	"stucco", "sugar", "suitcase", "sulfur", "summer", "sunset", "supply", "surf",
	"swallow", "swamp", "sweater", "swimming", "swivel", "sycamore", "syntax", "syrup",
	"tackle", "taffy", "tahini", "tambourine", "tandem", "tangerine", "tapir", "tarragon",
	"tassel", "tavern", "tea", "teapot", "tempo", "tender", "tennis", "terrace",
	"textbook", "thaw", "thicket", "thimble", "thistle", "thunder", "ticket", "tide",
	"tiger", "tile", "timber", "tin", "toast", "toffee", "toledo", "tomato",
	"tonga", "topaz", "torch", "tornado", "tortilla", "toucan", "touchdown", "tourist",
	"tower", "trellis", "trout", "truck", "truffle", "trumpet", "tulip", "tundra",
	"tunnel", "turquoise", "turtle", "tuxedo", "twine", "typewriter", "typhoon",
	"ukulele", "umpire", "unicorn", "unify", "universe", "upland", "uranium", "urchin",
	"utensil", "utopia",
	"vacation", "valley", "vanilla", "vaseline", "vault", "velvet", "vendor", "veranda",
	"verbena", "vertex", "vessel", "viaduct", "vibrant", "victory", "video", "viking",
	"village", "vine", "vinegar", "violet", "viola", "viper", "visa", "vision",
	"volcano", "volleyball", "voucher", "vulture", "vortex",
	"waffle", "wagon", "walnut", "walrus", "wanderer", "wardrobe", "warmth", "wasabi",
	"waterfall", "wattle", "weather", "weasel", "welder", "whale", "wheat", "wheel",
	"whisker", "whistle", "wildflower", "willow", "window", "windstorm", "winter", "wire",
	"wisteria", "wombat", "woodland", "wreath", "wrench", "wren", "xylophone",
	"yacht", "yak", "yam", "yardstick", "yarrow", "yeast", "yellow", "yeti",
	"yodel", "yogurt", "yoke", "yucca", "yurt",
	"zebra", "zenith", "zeppelin", "zephyr", "ziggurat", "zinc", "zinnia", "zipper",
	"zircon", "zodiac", "zombie", "zucchini",

	"abacus", "abrupt", "absorb", "abyss", "accent", "accordion", "acrobat", "adjust",
	"aerial", "agenda", "agile", "aisle", "alert", "alkali", "alley", "almond",
	"alto", "ammonia", "amethyst", "anchor", "angular", "ankle", "anthem", "antic",
	"apex", "apricot", "arbor", "arcade", "armada", "array", "artisan", "asparagus",
	"aspect", "asphalt", "auction", "audit", "auger", "austere", "author", "avenue",
	"avid", "axis", "baboon", "backdrop", "bagpipe", "bakery", "balmy", "banyan",
	"barley", "barometer", "bayou", "beagle", "beaver", "bedlam", "beeline", "bell",
	"bellow", "bench", "bergamot", "bestow", "bicep", "billow", "bingo", "bisque",
	"bitters", "blazer", "blizzard", "blueberry", "blunt", "boardwalk", "bobbin", "bolt",
	"bonanza", "bonsai", "booth", "botanic", "bounce", "bourbon", "boxcar", "bravado",
	"brawn", "brisk", "broccoli", "brochure", "brunt", "bulldog", "bungalow", "bunker",
	"buoy", "burly", "buttercup", "cable", "cameo", "canary", "capsule", "caravan",
	"carillon", "carnival", "cascade", "cashew", "casino", "castor", "catkin", "cauliflower",
	"cavern", "cayenne", "centaur", "ceramic", "chapel", "chariot", "chasm", "cheddar",
	"cheetah", "chime", "chowder", "chrome", "chrysalis", "cinder", "citadel", "civil",
	"clarion", "climate", "clock", "cobblestone", "coexist", "cognac", "colander", "collarbone",
	"colt", "condor", "conifer", "convex", "copier", "corridor", "costume", "courage",
	"cradle", "crater", "crayfish", "cruise", "crumb", "cubicle", "cuff", "currant",
	"cutlass", "cyclone", "cymbal", "daffodil", "daiquiri", "damson", "dandelion", "date",
	"debut", "decibel", "decoy", "deluxe", "depot", "derby", "dialog", "diesel",
	"dinner", "divisor", "dodge", "dole", "donut", "dossier", "dovetail", "doze",
	"duplex", "eaglet", "echidna", "eclair", "effort", "eight", "elbow", "elk",
	"elongated", "elysian", "emberglow", "empire", "enamel", "energy", "escape", "eucalyptus",

	"falconer", "farthing", "fathom", "felt", "fife", "fjordland", "flaming", "flotilla",
	"fluorescent", "fogbank", "forever", "fortress", "fragrance", "freesia", "fresco", "fringe",
	"frolic", "fulcrum", "fumarole", "gazania", "heirloom",
}
